#!/usr/bin/env rake
require 'gris/setup'
require 'dotenv'
Gris.load_environment

require File.expand_path('../config/application.rb', __FILE__)
require 'json'

Dir.glob('./lib/tasks/*.rake').each { |r| import r }
